### ISSUE TITLE
Video Panel not showing iFrame feed when it used to, even after upgrading to the latest version

### ISSUE THREAD

**Issue by ccasteel-max** [innius/grafana-video-panel#11]
Video Panel not showing iFrame feed when it used to, even after upgrading to the latest version

**Comment by rvdwijngaard** [comment]
Hi @ccasteel-max can you provide me some more details about your scenario? A screenshot might help

**Comment by ccasteel-max** [comment]
![image](https://user-images.githubusercontent.com/89144659/133304818-d56f0e46-d939-4f2a-ac75-91555a435cb7.png)
 Sure. The iframe link works just fine in its own tab so I know it's not that.

**Comment by rvdwijngaard** [comment]
It's still a bit hard for me to say anything about this issue since I am still missing context. Are you sure this link supports being used as an iframe? Most public services only work if you use the embedded link. 

**For example:**
This url does not work (although it works fine as standalone): https://vimeo.com/248012337 
This url works: https://player.vimeo.com/video/248012337?h=cbff20ee79

**Comment by ccasteel-max** [comment]
I have a URL: http://10.0.1.8:7002/player.html

That when I open in another tab works just fine. And again used to work with your plugin.

The links you sent work just fine. So I’m not sure what the problem is.

I type in my url from 10.0.1.8 and nothing happens. It’s just blanks. I don’t know what more information I can provide.

**Comment by theotherguy2175** [comment]
Why has this been closed?
