### ISSUE TITLE
Video does not automatically start when using panel in Grafana Playlist

### ISSUE THREAD

**Issue by CollistaR** [innius/grafana-video-panel#23]
Hello over there!

Indeed a very nice plugin to display a video from YouTube but unfortunately when I added the dashboard with the video plugin to the Grafana Playlist (slide show between dashboards), the video would start only at the very first iteration through the playlist but not anymore. After first iteration I must manually click on the start button on the video.

**Comment by rvdwijngaard** [comment]
Hello @CollistaR 

Thanks for reporting this issue. It don't think I can find a proper explanation for this behavior. I have created two dashboards in which one plays a video using this plugin. I have added both dashboards to a playlist and start it. I noticed that the video is played once and if it is finished it is never started again unless I start it manually. 

Unfortunately I cannot find any explanation for this issue. I have tried to ensure a unique URL is created each time the dashboard is rendered. I have done that by using an iframe with the youtube URL and the `$__from parameter. For example: `https://www.youtube.com/embed/051wmmDNJnc?si=xff_l8ZBqULg9ooW&controls=0&autoplay=1&&loop=1&id=${__from}` Unfortunately this does not seem to solve the problem. 

I took another approach: play an mp4 video from another source which seems to work properly. If you look in the debugger of your browser you'll notice that playing a video makes more requests on google apis than you would expect. I suspect this issue is behavior of youtube api rather than this plugin.
